github.com:
    users:
        mikathedev:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: mikathedev
