# ~/.config/hypr/hyprpaper.conf

ipc = on

splash = false

wallpaper {
    monitor =   # Leave empty for fallback (applies to all monitors)
    path = /home/mika/wallpaper.png
    # fit_mode = cover  # Optional: default is cover; options: contain, cover, fill, tile
}
